### ISSUE TITLE
Base url issue

### ISSUE THREAD

**Issue by hpinkos** [CesiumGS/cesium-webpack-example#11]
From https://github.com/AnalyticalGraphicsInc/cesium/issues/6319#issuecomment-410764699

> The documentation for Cesium and Webpack appears to be broken around 1.47, 1.48 . Whenever the iframe implementation was enforced as the dom container for the map.

---

> Heads up, I figured it out.
>
>`CESIUM_BASE_URL : JSON.stringify('')`
>now needs to be
>`CESIUM_BASE_URL : JSON.stringify('../')`

**Comment by ggetz** [comment]
Thanks @hpinkos, you beat me to it. This should be updated both in this repo and in the cesiumjs.org tutorial as well.
