### ISSUE TITLE
createWorldTerrain not found in cesium

### ISSUE THREAD

**Issue by zxyfreediver** [CesiumGS/cesium-webpack-example#44]
I cloned the cesium-webpack-example and try to run it on localhost. errors show that no createWorldTerrain in "cesium".
and then, I checked the API doc, and found it should be createWorldTerrainAsync. 
I think the cesium-webpack-example uses the old version of cesium and it should be updated.

createWorldTerrain -> createWorldTerrainAsync
createOsmBuildings -> createOsmBuildingsAsync

**Comment by FuXiangGit** [comment]
I hava the same problem

**Comment by zxyfreediver** [comment]
> 

you can update the two api in your code like
createOsmBuildings() -> await createOsmBuildingsAsync()

it works for me

**Comment by dmanchester** [comment]
I encountered this issue, too, with Cesium v1.108.

The main Cesium repo's [`CHANGES.md`](https://github.com/CesiumGS/cesium/blob/main/CHANGES.md) indicates `createWorldTerrain` and `createOsmBuildings` were deprecated in v1.104 and removed in v1.107, having been replaced by async counterparts.
