### ISSUE TITLE
Cesium 1.110 webpack update  

### ISSUE THREAD

**Issue by selimsezr** [CesiumGS/cesium-webpack-example#46]
![image](https://github.com/CesiumGS/cesium-webpack-example/assets/46382683/b0707bff-ebe3-4dc4-ae25-1f5f42e34f8b)

**Comment by bbhxwl** [comment]
> ![image](https://user-images.githubusercontent.com/46382683/274889823-b0707bff-ebe3-4dc4-ae25-1f5f42e34f8b.png)

What is the latest version available now? Nuxt2, webpack4

**Comment by selimsezr** [comment]
I solved it [this](https://community.cesium.com/t/cesium-ion-1-110-webpack-problem/27351/2?u=selim_sezer) way

**Comment by bbhxwl** [comment]
> I solved it [this](https://community.cesium.com/t/cesium-ion-1-110-webpack-problem/27351/2?u=selim_sezer) way

How can I use nuxtjs? I don't know how to modify specific code, and I don't know nextjs. Can you help me?
