### ISSUE TITLE
Is CESIUM_BASE_URL even still involved in worker setup and do they still need to be copied around?

### ISSUE THREAD

**Issue by katSchmid** [CesiumGS/cesium-webpack-example#54]
Is CESIUM_BASE_URL even still involved in worker setup and do they still need to be copied around?

**Comment by jjspace** [comment]
@katSchmid yes CesiumJS still needs to load the worker files at runtime so they need to be accessible. The `CESIUM_BASE_URL` value helps point to the path where those files will be located so it needs to be set as well. If they are at the root of your site  you can set `CESIUM_BASE_URL` to an empty string (`""`)

**Comment by jjspace** [comment]
I'm going to close this issue for now. If you have any problems feel free to open a new one. This example was just updated so maybe it can provide more guidance
